### ISSUE TITLE
webserver documentation not correct

### ISSUE THREAD

**Issue by Timtower** [overwolf/overwolf.github.io#1010]
https://github.com/overwolf/overwolf.github.io/blob/source/website/pages/docs/api/web/webserver.mdx

overwolf.web.webserver does not exist anymore.
overwolf.web has no listen method, it is createServer.

Would it be possible to get somebody into the code and fix the documentation?

**Comment by OdedItkinOW** [comment]
Hi!
Took a while, but I'm going over it now:
The namespaces weren't actually changed, but the documentation is simply unclear.

The way the overwolf.web api works, is that overwolf.web creates a websocket/webserver, and then the returned objects correspond to overwolf.web.websocket/overwolf.web.webserver respectively
![image](https://user-images.githubusercontent.com/104757378/193444545-c7317fc2-fce4-47f5-b35e-4b5f3da41a7e.png)
![image](https://user-images.githubusercontent.com/104757378/193444557-d27a9f79-9179-4b93-8bf5-2c15aefb2eb0.png)

Will update the documentation to better reflect that, and then update this issue

**Comment by OdedItkinOW** [comment]
For now, added an extra clarification in commit dfdc4a47046091c66f0047f5af64d7f0ea261b7a, will be revisited in the near future with a more permanent fix

**Comment by Timtower** [comment]
Does this mean that I can host files from within the opk with this?

Want to use it to give a browser page without having a dedicated webhost.

**Comment by OdedItkinOW** [comment]
It is impossible to use the overwolf.web.webserver api to host files etc, as it is intended just for receiving messages into the app.
It should be possible to do with a "normal" webserver that runs inside of the app however

**Comment by Timtower** [comment]
And does that give me the ability to use files that are normally inside the opk?
Or do I need to extract those somehow?

**Comment by OdedItkinOW** [comment]
There is no limitation from the overwolf platform side that would stop an app from hosting those files in standard methods, so it should be fine

**Comment by Timtower** [comment]
Good enough for now, will ask further questions in devs-help in discord for now as it goes outside the scope of this issue.
