### ISSUE TITLE
Missing information in submit-your-app-to-the-store.md

### ISSUE THREAD

**Issue by Bl0n** [overwolf/overwolf.github.io#405]
These issues are regarding `submit-your-app-to-the-store.md`

There's a broken image under the **3. ScreenshotX.jpg** header.

It also mentions implementing a video in the app store, and says "see store.json information below".
However, there is no further information on implementing a video anywhere on the page (or elsewhere as far as I can find.)

**Comment by eransharv** [comment]
@Bl0n missing image fixed.
Regarding video instruction - I forward it to the relevant team. I update the site once I get an answer.
Thanks!

**Comment by eransharv** [comment]
@Bl0n fixed the issue. I removed the paragraph about the video, as currently it's not supported.
Thanks!
