### ISSUE TITLE
Broken footer links on support.overwolf.com

### ISSUE THREAD

**Issue by Bl0n** [overwolf/overwolf.github.io#407]
On any (Freshdesk) support.overwolf.com page, the following links in the footer are just redirecting to the current page:

* Overwolf platform
* Download
* Partner with us

**Comment by eransharv** [comment]
@Bl0n thanks for all the pull requests! That is very helpful. 
Regarding this issue - I will make sure that the support team will fix it.

**Comment by Bl0n** [comment]
No problem! Just trying to help make making Overwolf apps a little easier. 👍
