### ISSUE TITLE
"Please don't use HTML tags."

### ISSUE THREAD

**Issue by Arco-Dielhof** [overwolf/overwolf.github.io#931]
On the page Update Store Listing, in the part "[Full Description](https://github.com/overwolf/overwolf.github.io/blob/source/docs/topics/update-store-listing.md#full-description)", it asks specifically not to use HTML tags, but plain text or markdown instead. However, the example picture underneath, actually shows the 'do not use' HTML tags. :P
Here is a picture with the same text, as well as the markdown format, if you rather not use the superior dark mode ;)

```
### Record. Watch. Improve!
To become a pro, train like a pro - WolfTrainer.  
WolfTrainer records your game and so you can comfortably watch every kill, death, mis-click, wrong timing, awesome gank, baron steal and other major match events until you know how to get better.  
With the WolfTrainer you can:
- Record an entire match and watch on desktop
- Quickly navigate to major events with detailed timeline
- Add your own timeline marks in-game
- Review some key performance stats
- Set your video quality and control storage option, and much more!
```

![image](https://user-images.githubusercontent.com/56220993/156008845-e2618459-4acc-4e4b-b0ff-eb37e0bfc4d7.png)

**Comment by adircoh** [comment]
Thank you for the feedback
